"""
SetupHelper — 一键初始化 Ansible 环境。

流程: Ubuntu生成SSH密钥 → 分发公钥到所有VM → 生成inventory → 验证连通性
"""

from __future__ import annotations
import logging
from typing import Any
import paramiko
from ansible_runner import AnsibleRunner

logger = logging.getLogger(__name__)


class SetupHelper:
    """处理 Ansible 环境的首次初始化。"""

    def __init__(self, config: dict, runner: AnsibleRunner):
        self._config = config
        self._runner = runner
        self._managed_nodes: list[dict] = config.get("managed_nodes", [])

    # ── Step 1: 生成 SSH 密钥对 ─────────────────────────────

    def _generate_ssh_key(self) -> str:
        """在Ubuntu上生成RSA密钥对(如不存在)，返回公钥内容。"""
        logger.info("Step 1: 检查/生成SSH密钥对")
        ec, out, _ = self._runner.execute("cat ~/.ssh/id_rsa.pub 2>/dev/null")
        if ec == 0 and out.strip():
            logger.info("密钥已存在，跳过生成")
            return out.strip()

        logger.info("生成新密钥对...")
        self._runner.execute('ssh-keygen -t rsa -b 2048 -N "" -f ~/.ssh/id_rsa')
        ec, pubkey, _ = self._runner.execute("cat ~/.ssh/id_rsa.pub")
        if ec != 0 or not pubkey.strip():
            raise RuntimeError("SSH密钥生成失败")
        logger.info("密钥生成成功")
        return pubkey.strip()

    # ── Step 2-3: 分发公钥 ──────────────────────────────────

    def _install_pubkey(self, node: dict, pubkey: str) -> bool:
        """在单台VM上安装公钥到authorized_keys。"""
        host, user, pwd = node["host"], node["user"], node.get("password", "")
        name = node.get("name", host)
        logger.info("分发公钥到 %s (%s@%s)", name, user, host)

        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        try:
            client.connect(hostname=host, port=22, username=user,
                           password=pwd, timeout=10,
                           allow_agent=False, look_for_keys=False)
            cmds = [
                "mkdir -p ~/.ssh", "chmod 700 ~/.ssh",
                f"echo '{pubkey}' >> ~/.ssh/authorized_keys",
                "chmod 600 ~/.ssh/authorized_keys",
                "restorecon -R ~/.ssh 2>/dev/null || true",
            ]
            for cmd in cmds:
                stdin, stdout, stderr = client.exec_command(cmd, timeout=10)
                stdout.channel.recv_exit_status()
            logger.info("公钥安装成功: %s", name)
            return True
        except Exception as e:
            logger.error("安装公钥失败 %s: %s", name, e)
            return False
        finally:
            try:
                client.close()
            except Exception:
                pass

    def _distribute_keys(self, pubkey: str) -> dict[str, bool]:
        """分发公钥到所有被管节点。"""
        results = {}
        for node in self._managed_nodes:
            name = node.get("name", node["host"])
            results[name] = self._install_pubkey(node, pubkey)
        return results

    # ── Step 4: 生成 inventory ──────────────────────────────

    def _generate_inventory(self) -> str:
        """在Ubuntu上生成Ansible inventory文件。"""
        logger.info("Step 4: 生成inventory: %s", self._runner.inventory_path)
        import os
        remote_dir = os.path.dirname(self._runner.inventory_path)
        self._runner.execute(f"mkdir -p {remote_dir}")

        groups: dict[str, list[dict]] = {}
        for node in self._managed_nodes:
            for g in node.get("groups", []):
                groups.setdefault(g, []).append(node)

        lines = ["# Auto-generated by Ansible MCP Server", "", "[all]"]
        for node in self._managed_nodes:
            lines.append(
                f"{node['name']} ansible_host={node['host']} "
                f"ansible_user={node.get('user', 'ansible')}"
            )
        lines.append("")
        for gname, nodes in groups.items():
            if gname == "all":
                continue
            lines.append(f"[{gname}]")
            for n in nodes:
                lines.append(n["name"])
            lines.append("")
        lines += [
            "[all:vars]",
            "ansible_ssh_private_key_file=~/.ssh/id_rsa",
            "ansible_ssh_common_args='-o StrictHostKeyChecking=no'",
            "",
        ]
        content = "\n".join(lines)
        self._runner.upload_content(content, self._runner.inventory_path)
        logger.info("Inventory生成完毕")
        return content

    # ── Step 5: 验证 ────────────────────────────────────────

    def _verify(self) -> str:
        """运行 ansible all -m ping 验证连通性。"""
        logger.info("Step 5: 验证所有节点连通性...")
        ec, out, err = self._runner.ansible_module(
            "all", module="ping", args="", become=False)
        return out if out else err

    # ── 主入口 ──────────────────────────────────────────────

    def run_setup(self) -> dict[str, Any]:
        """执行完整一键初始化，返回各步骤状态。"""
        result: dict[str, Any] = {"status": "success", "steps": {}}
        try:
            self._runner.connect()
            pubkey = self._generate_ssh_key()
            result["steps"]["ssh_keygen"] = {
                "status": "ok", "preview": pubkey[:80] + "..."
            }
            dist = self._distribute_keys(pubkey)
            failed = [k for k, v in dist.items() if not v]
            result["steps"]["key_distribution"] = {
                "status": "ok" if not failed else "partial",
                "results": dist, "failed": failed,
            }
            inv = self._generate_inventory()
            result["steps"]["inventory"] = {"status": "ok", "content": inv}
            vout = self._verify()
            result["steps"]["verify"] = {
                "status": "ok" if "UNREACHABLE" not in vout else "partial",
                "output": vout,
            }
        except Exception as e:
            result["status"] = "error"
            result["error"] = str(e)
            logger.exception("初始化失败")
        return result
